const PlayerActionTypes={
    DOMINO_CLICK_ACTION:"DOMINO_CLICK_ACTION",
    DOMINO_ACTION:"DOMINO_ACTION",
    PASS_ACTION:"PASS_ACTION",
    ON_REMOVE_DOMINO_ANIMATION_COMPLETE:"ON_REMOVE_DOMINO_ANIMATION_COMPLETE",
    DISCARD_ACTION:"DISCARD_ACTION",
    ON_TIMER_COMPLETE:"ON_TIMER_COMPLETE",
}

export default PlayerActionTypes