const UIActionTypes={
    INIT_UI_ACTION:"INIT_UI_ACTION",
    HIDE_GAME_MENU:"HIDE_GAME_MENU",
    UPDATE_GAME_STATE_ACTION:"UPDATE_GAME_STATE_ACTION",
    PLAYER_JOIN_ACTION:"PLAYER_JOIN_ACTION",
    PLAYER_HAND_ACTION:"PLAYER_HAND_ACTION",
    SHOW_HAND_ACTION:"SHOW_HAND_ACTION",
    PLAYER_TURN_ACTION:"PLAYER_TURN_ACTION",
    HIDE_ALL_PLAYER_TIMER_ACTION:"HIDE_ALL_PLAYER_TIMER_ACTION",
    DISCARD_ACTION:"DISCARD_ACTION"
}

export default UIActionTypes
