const PileActionTypes={
    ADD_DOMINO_ACTION:"ADD_DOMINO_ACTION",
    LOCAL_PLAYER_ACTION:"LOCAL_PLAYER_ACTION",
    RESET_ACTION:"PLAYERRESET_ACTION_HAND_ACTION",

    ON_INSERT_DOMINO_ANIMATION_COMPLETE:"ON_INSERT_DOMINO_ANIMATION_COMPLETE"
}

export default PileActionTypes